name: Build OpenWrt Packages

on:
  workflow_dispatch:
  push:
    branches:
      - feeds
    paths:
      - 'packages/**'

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: feeds

      - name: Create VG & LV
        run: |
          mnt_size=$(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//')
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 2)
          sudo truncate -s "$mnt_size"G /mnt/mnt.img
          sudo truncate -s "$root_size"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner

      - name: Mount LV
        run: |
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner:runner /builder
          df -Th

      - name: Fetch Packages
        run: |
          feeds_list=$(curl -s "https://raw.githubusercontent.com/${{ github.repository }}/feeds/packages.txt")
          echo "packages_list=$feeds_list" >> $GITHUB_ENV

      - name: Build Packages
        uses: pmkol/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_lite
          PACKAGES: ${{ env.packages_list }}
          INDEX: 1
          KEY_BUILD: ${{ secrets.OPENWRT_PRIVATE_KEY }}
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload packages_lite
        run: |
          mkdir -p /tmp/openwrt_pkgs/${{ matrix.arch }}/
          mv bin/packages/${{ matrix.arch }}/packages_lite/* /tmp/openwrt_pkgs/${{ matrix.arch }}
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: packages

      - name: Git push
        continue-on-error: true
        run: |
          rm -rf openwrt_pkgs/23.05/${{ matrix.arch }}
          mkdir -p openwrt_pkgs/23.05/${{ matrix.arch }}
          mv /tmp/openwrt_pkgs/${{ matrix.arch }} ./openwrt_pkgs/23.05
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add openwrt_pkgs/23.05/${{ matrix.arch }}
          if ! git diff-index --quiet HEAD --; then
            git commit -sm "Update packages_lite - ${{env.latest_release}}"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:packages --force
          else
            echo "No changes to commit, skipping push."
          fi
