name: Build OpenWrt Packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}-${{ matrix.tag }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64_generic
          - x86_64
        tag:
          - openwrt-23.05

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: feeds

      - name: Build Packages
        uses: pmkol/openwrt-gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.tag }}
          FEEDNAME: packages_lite
          PACKAGES: samba4
          INDEX: 1
          KEY_BUILD: ${{ secrets.OPENWRT_PRIVATE_KEY }}
          NO_REFRESH_CHECK: true
          IGNORE_ERRORS: true

      - name: Upload packages_lite
        run: |
          mkdir -p /tmp/openwrt_pkgs/${{ matrix.arch }}/
          mv bin/packages/${{ matrix.arch }}/packages_lite/* /tmp/openwrt_pkgs/${{ matrix.arch }}
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: packages

      - name: Git push
        continue-on-error: true
        run: |
          rm -rf openwrt_pkgs/23.05/${{ matrix.arch }}
          mkdir -p openwrt_pkgs/23.05/${{ matrix.arch }}
          mv /tmp/openwrt_pkgs/${{ matrix.arch }} ./openwrt_pkgs/23.05
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add openwrt_pkgs/23.05/${{ matrix.arch }}
          if ! git diff-index --quiet HEAD --; then
            git commit -sm "Update ${{ matrix.arch }} packages_lite - ${{env.latest_release}}"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:packages --force
          else
            echo "No changes to commit, skipping push."
          fi
