name: Build OpenWrt Feeds Test(lite-23.05)

on:
  workflow_dispatch:
  push:
    branches:
      - lite-23.05

jobs:
  push:
    name: Push Built Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: packages
      
      - name: Download packages
        run: |
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV
          git filter-branch --prune-empty --subdirectory-filter . HEAD~1..HEAD
          rm -rf openwrt_lite/23.05/*
          curl -LO https://github.com/${{ github.repository }}/releases/download/openwrt-23.05/packages-lite-x86_64.tar.xz
          curl -LO https://github.com/${{ github.repository }}/releases/download/openwrt-23.05/packages-lite-aarch64_generic.tar.xz
          for file in packages-lite-*.tar.xz; do tar -xf "$file" -C openwrt_lite/23.05; done
          rm -f packages-lite-*.tar.xz

      - name: Git push
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add openwrt_lite/23.05/*
          git commit -sm "[${{env.latest_release}}] Update packages lite-23.05"
          git push --force
