name: Build OpenWrt Feeds Test(lite-23.05)

on:
  workflow_dispatch:
  push:
    branches:
      - lite-23.05

jobs:
  push:
    name: Push Built Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: packages
      
      - name: Download packages
        run: |
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV
          reset_commit=$(git rev-list --max-parents=0 HEAD)
          git reset --hard "$reset_commit"
          echo "$(date +%s%N)" > openwrt_lite/23.05/x86_64/random_file.txt

      - name: Git push
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add openwrt_lite/23.05/*
          git commit -sm "[${{env.latest_release}}] Update packages lite-23.05"
          git push --force
