name: Update OpenWrt Feeds(Lite)

on:
  workflow_dispatch:

jobs:
  sync:
    name: Sync Upstream
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: feeds

      - name: Update Feeds
        run: |
          bash update-feeds.sh
          echo "latest_release=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Git Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add lite
          if ! git diff-index --quiet HEAD --; then
            git commit -sm "Sync upstream up to ${{env.latest_release}}"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:feeds --force
          else
            echo "No changes to commit, skipping push."
          fi
